---
- name: Getting mounts
  hosts: Test
  tasks:
  - name: DISK
    shell: /bin/df -T
    register: diskstd
  - debug:
     var: diskstd
     
  - name: service start
    service:
      name: httpd
      state: started
      enabled: no 
...
